name: Fraud Detection
on: [push, workflow_dispatch]

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Git LFS
        run: git lfs install
      - name: Fetch LFS Files
        run: git lfs fetch && git lfs pull
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install xgboost
      - name: Run executable bash script
        run: bash ./run.sh
      - name: Status
        run: |
          echo "Done"
